name: vocabulary_advancer
description: Vocabulary Advancer sample app

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.16.1
  intl: ^0.16.0
  http: ^0.12.0
  chopper: ^3.0.1
  json_annotation: ^3.0.0
  logger: ^0.8.3
  cached_network_image: ^2.0.0
  get_it: ^4.0.0
  provider: ^4.0.4
  flutter_typeahead: ^1.7.0
  shared_preferences: ^0.5.6+3

dev_dependencies:
  build_runner: ^1.7.3
  chopper_generator: ^3.0.3
  json_serializable: ^3.2.3
  lint: ^1.1.1
  test: any
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 700